// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoG3A9bTj3xrT3aTwJgz1h5ztukxaKdL4',
    appId: '1:331475566135:web:9dca5925a218c3798a49b2',
    messagingSenderId: '331475566135',
    projectId: 'financial-dashboard-e22b7',
    authDomain: 'financial-dashboard-e22b7.firebaseapp.com',
    storageBucket: 'financial-dashboard-e22b7.firebasestorage.app',
    measurementId: 'G-DYTH9SSR2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAul81k-QI_CzDQpzAQAJZ9-xcOquMrmD0',
    appId: '1:331475566135:android:28d92e23a252a72c8a49b2',
    messagingSenderId: '331475566135',
    projectId: 'financial-dashboard-e22b7',
    storageBucket: 'financial-dashboard-e22b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLW7OaWJNUI__XOiCJrf5hKGKnGmzeB3Q',
    appId: '1:331475566135:ios:031818a10fbb1d4a8a49b2',
    messagingSenderId: '331475566135',
    projectId: 'financial-dashboard-e22b7',
    storageBucket: 'financial-dashboard-e22b7.firebasestorage.app',
    iosBundleId: 'com.example.financialDashbaord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLW7OaWJNUI__XOiCJrf5hKGKnGmzeB3Q',
    appId: '1:331475566135:ios:031818a10fbb1d4a8a49b2',
    messagingSenderId: '331475566135',
    projectId: 'financial-dashboard-e22b7',
    storageBucket: 'financial-dashboard-e22b7.firebasestorage.app',
    iosBundleId: 'com.example.financialDashbaord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoG3A9bTj3xrT3aTwJgz1h5ztukxaKdL4',
    appId: '1:331475566135:web:45e6ccdf9580bfc68a49b2',
    messagingSenderId: '331475566135',
    projectId: 'financial-dashboard-e22b7',
    authDomain: 'financial-dashboard-e22b7.firebaseapp.com',
    storageBucket: 'financial-dashboard-e22b7.firebasestorage.app',
    measurementId: 'G-GKR739GK2Y',
  );
}
