name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Replace with your branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js (required for Firebase CLI)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match Firebase CLI's Node.js requirements

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      # Authenticate with Firebase
      - name: Authenticate with Firebase
        run: firebase auth:login:ci --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
